# Generated by Django 3.2.25 on 2024-06-07 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core.customer', verbose_name='Customer'),
            preserve_default=False,
        ),
    ]
