# Generated by Django 3.2.25 on 2024-06-07 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='technician',
        ),
    ]
