# Generated by Django 3.2.25 on 2024-06-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240607_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(default='test', max_length=120, verbose_name='Job Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='technician',
            field=models.CharField(default='test', max_length=120, verbose_name='Technician'),
            preserve_default=False,
        ),
    ]
